package blackjack;

public class BlackjackGUI extends javax.swing.JFrame {

    public BlackjackGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPelaaja = new javax.swing.JLabel();
        lbKortit = new javax.swing.JLabel();
        lbPisteet = new javax.swing.JLabel();
        lbNaytaPisteet = new javax.swing.JLabel();
        lbNaytaKortit = new javax.swing.JLabel();
        bnOtaKortti = new javax.swing.JButton();
        bnPelaaKasi = new javax.swing.JButton();
        mbMain = new javax.swing.JMenuBar();
        mPeli = new javax.swing.JMenu();
        miPelaa = new javax.swing.JMenuItem();
        miLopeta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPelaaja.setText("Pelaaja");

        lbKortit.setText("Kortit: ");

        lbPisteet.setText("Pisteet: ");

        lbNaytaPisteet.setText("Pisteet tähän");

        bnOtaKortti.setText("Ota Kortti");
        bnOtaKortti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOtaKorttiActionPerformed(evt);
            }
        });

        bnPelaaKasi.setText("Pelaa Käsi");
        bnPelaaKasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnPelaaKasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPisteet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNaytaPisteet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbKortit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPelaaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNaytaKortit))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bnOtaKortti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnPelaaKasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPelaaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKortit)
                    .addComponent(lbNaytaKortit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPisteet)
                    .addComponent(lbNaytaPisteet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnOtaKortti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnPelaaKasi)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        mPeli.setText("Peli");

        miPelaa.setText("Pelaa");
        miPelaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPelaaActionPerformed(evt);
            }
        });
        mPeli.add(miPelaa);

        miLopeta.setText("Lopeta");
        miLopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLopetaActionPerformed(evt);
            }
        });
        mPeli.add(miLopeta);

        mbMain.add(mPeli);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnOtaKorttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOtaKorttiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnOtaKorttiActionPerformed

    private void bnPelaaKasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnPelaaKasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnPelaaKasiActionPerformed

    private void miPelaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPelaaActionPerformed
        // Siirrä pelivuoro koneelle
    }//GEN-LAST:event_miPelaaActionPerformed

    private void miLopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLopetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miLopetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackjackGUI().setVisible(true);
            }
        });
        
        Korttipakka pelipakka = new Korttipakka(1);
        PelaajanKasi pelaaja = new PelaajanKasi();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnOtaKortti;
    private javax.swing.JButton bnPelaaKasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbKortit;
    private static javax.swing.JLabel lbNaytaKortit;
    private static javax.swing.JLabel lbNaytaPisteet;
    private javax.swing.JLabel lbPelaaja;
    private javax.swing.JLabel lbPisteet;
    private javax.swing.JMenu mPeli;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miLopeta;
    private javax.swing.JMenuItem miPelaa;
    // End of variables declaration//GEN-END:variables
}
